disabled_rules: # rule identifiers to exclude from running
  - line_length
  - cyclomatic_complexity
  - function_body_length
  - file_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
